import 'package:flutter/material.dart';

class AppColors {
  AppColors._(); // this basically makes it so you can't instantiate this class
  static const headingTextColor = Color(0xffFCFCFC);
  static const dotColor = Color(0xff4ECB71);
  static const elevatedColor = Color(0xff4ECB71);
  static const loginButtonColor = Color(0xff379050);
  static const transparent = Colors.transparent;
  static const allHeadColor = Color(0xff1D1D1F);
  static const subheadColor = Color(0xff434345);
  static const textInputField = Color(0xffF8F8F8);
  static const hintColor = Color(0xff7C7C7D);
  static const forgotpass = Color(0xff71D58D);
  static const appbarBoarder = Color(0xffD3D3D3);
  static const nondotcolor = Color(0xffF8F8F8);
  static const hoverColor = Color(0xffF4F4F4);
  static const hoverBoarderColor = Color(0xff9D9D9D);
  static const lightThemeback = Colors.white;
  static const darkThemeback = Color(0xff0D0D0D);
  static const darkSubHead = Color(0xffE0E0E2);
  static const darkTextInput = Color(0xff181818);
  static const darkhint = Color(0xff7C7C7D);
  static const darkAppBarboarder = Color(0xff393939);
  static const focusTextBoarder = Color(0xffAEE7BE);
  static const focusCursorColor = Color(0xff313131);
  static const errorColor = Color(0xffEB5757);
  static const errorback = Color(0xffFDEEEE);
  static const confirmValid = Color(0xff27AE60);
  static const disableButtonColor = Color(0xffAEE7BE);
  static const disableButtonTextColor = Color(0xff71D58D);
  static const homeBack = Color(0xffF8F8F8);
  static const primaryColor = Color(0xffFEFEFE);
  static const completeProfileColor = Color(0xffE9F7EF);
  static const disableNavIconColor = Color(0xff979797);
  static const navIconColor = Color(0xff4EcB71);
  static const profileHead = Color(0xff343434);
  static const bookingInvalid = Color(0xffA2A2A3);
  static const buttonwithvalue = Color(0xffC8EFD3);
  static const buttonmid = Color(0xff379050);
  static const disableSwitch = Color(0xffE6E0E9);
  static const disableswitchmiddle = Color(0xff79747E);
  static const profileDarkText = Color(0xffE0E0E2);
  static const booklight = Color(0xffFEFEFE);
  static const dateColor = Color(0xff4CBC7B);
  static const warningToast = Color(0xffF2994A);
  static const disableTime = Color(0xffEE7474);
  static const bookingShowColor = Color(0xffE9F7EF);
  static const totalbookingColor = Color(0xff82D0A3);
  static const cancelBooking = Color(0xffF39E9E);
  static const cancelBack = Color(0xffFDEEEE);
  static const roundColorBooking = Color(0xff35A756);
  static const requestedfriend = Color(0xff215AA6);
  static const announceDate = Color(0xffE9F7EF);
  static const successColor = Color(0xff27AE60);
}
