// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPPRkh90lUOJKMokUMKDkVaWSymmK5cvY',
    appId: '1:371309457718:web:064094ba425d0d37e44397',
    messagingSenderId: '371309457718',
    projectId: 'behrain-f2757',
    authDomain: 'behrain-f2757.firebaseapp.com',
    storageBucket: 'behrain-f2757.appspot.com',
    measurementId: 'G-W8VP6RSYGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPTaVNNBbPgtqWvJjIR5oEpfHiXAu3Wuo',
    appId: '1:371309457718:android:aaacf038925e0581e44397',
    messagingSenderId: '371309457718',
    projectId: 'behrain-f2757',
    storageBucket: 'behrain-f2757.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxhm8Zegk9lwEqe8DO7Bw5AzTX0E9FyFc',
    appId: '1:371309457718:ios:8c7e2bcd6ae32d71e44397',
    messagingSenderId: '371309457718',
    projectId: 'behrain-f2757',
    storageBucket: 'behrain-f2757.appspot.com',
    iosBundleId: 'com.example.tennisCourtBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxhm8Zegk9lwEqe8DO7Bw5AzTX0E9FyFc',
    appId: '1:371309457718:ios:be4c6631960f477ce44397',
    messagingSenderId: '371309457718',
    projectId: 'behrain-f2757',
    storageBucket: 'behrain-f2757.appspot.com',
    iosBundleId: 'com.example.tennisCourtBookingApp.RunnerTests',
  );
}
